# Repository settings for AI-HRMS-2025
# This file documents recommended repository settings
# These should be configured manually in GitHub repository settings

repository:
  name: AI-HRMS-2025
  description: "🤖 Enterprise-grade AI-powered Human Resource Management System with predictive analytics, multi-tenant architecture, and advanced recruitment tools"
  homepage: https://github.com/Spen-Zosky/AI-HRMS-2025
  topics:
    - ai
    - hr
    - hrms
    - human-resources
    - machine-learning
    - predictive-analytics
    - recruitment
    - ats
    - cv-parsing
    - skills-matching
    - multi-tenant
    - saas
    - nodejs
    - react
    - postgresql
    - vector-database
    - openai
    - anthropic
    - enterprise

  # Repository features
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  has_discussions: true

  # Security
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_auto_merge: true
  delete_branch_on_merge: true
  allow_update_branch: true

# Branch protection rules
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "Code Quality Checks"
          - "Security Scanning"
          - "Tests"
          - "Frontend Build"
          - "Integration Tests"
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: true
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false

  - name: develop
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "Code Quality Checks"
          - "Tests"
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false

# Environments
environments:
  - name: production
    protection_rules:
      - type: required_reviewers
        reviewers:
          - Spen-Zosky
      - type: wait_timer
        minutes: 5

  - name: staging
    protection_rules:
      - type: required_reviewers
        reviewers:
          - Spen-Zosky