name: Bug Report
description: File a bug report to help us improve AI-HRMS-2025
title: "[BUG] "
labels: ["bug", "triage"]
assignees: ["Spen-Zosky"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛

        Please search existing issues before submitting to avoid duplicates.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of the bug
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: A clear and concise description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: A clear and concise description of what actually happened
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application is affected?
      options:
        - Frontend (React)
        - Backend (Node.js/Express)
        - Database (PostgreSQL)
        - Authentication
        - AI Services (CV parsing, job matching)
        - HR Copilot
        - Analytics
        - Skills Management
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System unusable)
        - High (Major functionality affected)
        - Medium (Some functionality affected)
        - Low (Minor issue)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Tell us about your environment
      value: |
        - OS: [e.g. macOS 12.0, Ubuntu 20.04, Windows 11]
        - Node.js: [e.g. 18.15.0]
        - Browser: [e.g. Chrome 98.0, Firefox 95.0]
        - Version: [e.g. 1.0.0]
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Console Logs/Error Messages
      description: Please copy and paste any relevant log output
      placeholder: Paste console logs, error messages, or stack traces here
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: You can drag and drop images here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have provided all the requested information
          required: true
        - label: I have read the contributing guidelines
          required: false